version: '3.8'

services:
  vienna-hacking-bootcamp:
    build: .
    ports:
      - "9004:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    container_name: vienna-bootcamp-platform
    
    # Optional: Add resource limits
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    
    # Health check
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: vienna-bootcamp-network 